---
- hosts: all
  become: true
  tasks:
    - name: remove docker images
      shell: docker images rm -f bhuvaneshwaran14/project:latest
    - name: create docker container
      shell: docker run -itd  --name webapp -p 80:8080 bhuvaneshwaran14/project:latest
