---
- hosts: all
  become: true
  tasks:
    - name: stop container
      shell: docker stop demo
    - name: remove container
      shell: docker rm -f demo
    - name: remove container
      shell: docker rmi -f bhuvaneshwaran14/demo:latest
    - name: create docker container
      shell: docker run -itd  --name demo -p 80:8080 bhuvaneshwaran14/demo:latest
